// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgresdb_sql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Chart struct {
	Id                    uuid.UUID
	CreatedAt             time.Time
	ModifiedAt            time.Time
	IsArchived            bool
	IsDeleted             bool
	Title                 string
	Type                  string
	Query                 string
	DatabaseId            uuid.UUID
	CategoricalColumnName sql.NullString
	ValueColumnName       sql.NullString
}

type Database struct {
	Id               uuid.UUID
	CreatedAt        time.Time
	ModifiedAt       time.Time
	IsArchived       bool
	IsDeleted        bool
	Name             string
	Type             int32
	ConnectionString string
	Schema           pqtype.NullRawMessage
	LastSync         sql.NullTime
}
